services:
  api:
    profiles: [ full ]
    image: migrate-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - '.env'
      - '.docker.env'
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_TCP_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_SCHEMA}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h ${DB_HOST} -p${DB_PASSWORD}' ]
      interval: 10s
      timeout: 10s
      retries: 5

  minio:
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://${MINIO_HOST}:${MINIO_PORT}/minio/health/live' ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  minio_data:
